"""Define shared application constants."""

from pathlib import Path


class Omit:
    """Represent an omitted value."""


OMIT = Omit()

# Application directory and configuration
APP_DIRECTORY = Path(".loop")
APP_CONFIGURATION_FILENAME = "config.toml"

# Default backend configuration constants
DEFAULT_BASE_URL = "http://localhost:8000/v1"
DEFAULT_MODEL = "nvidia/Qwen3.6-35B-A3B-NVFP4"
DEFAULT_API_KEY = "local-api-key"

# Default agent configuration constants
DEFAULT_AGENT_NAME = "Loop"
TEMPORARY_DIRECTORY_PREFIX = "loop-"
TEMPORARY_CONTENT_DIRECTORY_PREFIX = "loop-content-"

# Marker file for identifying the root of a Loop project.
GIT_DIRECTORY = Path(".git")

# Session-related constants
SESSION_DATABASE_FILENAME = "sessions.db"
TELEMETRY_DATABASE_FILENAME = "telemetry.db"
OPERATIONAL_LOG_FILENAME = "loop.log"
DEFAULT_SESSION_NAME = "Untitled session"
INITIAL_SESSION_NAME_MAX_CHARS = 48
SESSION_NAME_MAX_CHARS = 80
SESSION_TITLE_CONTEXT_MAX_CHARS = 500
SESSION_TITLE_MAX_WORDS = 6
DEFAULT_COMPACTION_THRESHOLD = 0.8
DEFAULT_AGENT_MAX_TURNS = 25

# Structured-output resilience defaults
DEFAULT_STRUCTURED_OUTPUT_MODE = "auto"
DEFAULT_STRUCTURED_OUTPUT_MAX_RETRIES = 1
MAX_STRUCTURED_OUTPUT_DIAGNOSTIC_CHARS = 2_000
DEFAULT_HYPERPARAMETER_POLICY = "fallback"

# Permissions-related constants
PERMISSIONS_FILENAME = "permissions.yaml"
PERMISSIONS_AUDIT_FILENAME = "permissions-audit.jsonl"
DEFAULT_PERMISSIONS_AUDIT_BYTES = 5 * 1024 * 1024
DEFAULT_PERMISSIONS_AUDIT_BACKUPS = 3

# HTTP request constants
DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:153.0) Gecko/20100101 Firefox/153.0"
)
MAX_REDIRECTS = 5

# Ignore files
AGENT_IGNORE_FILENAME = ".agentignore"
GIT_IGNORE_FILENAME = ".gitignore"
IGNORE_FILENAMES = (GIT_IGNORE_FILENAME, AGENT_IGNORE_FILENAME)

# Default filenames and directories for agents and skills
DEFAULT_AGENTS_FILENAME = "AGENTS.md"
DEFAULT_AGENT_INSTRUCTIONS_SOURCE = "loop.agent/instructions.md"
DEFAULT_AGENT_INSTRUCTIONS_VERSION = "1"
DEFAULT_SKILL_FILENAME = "SKILL.md"
DEFAULT_SKILLS_DIRECTORY = Path(".agents/skills")
RESOURCE_DIRECTORIES = ("references", "scripts", "assets")
TRUNCATION_MARKER = "\n\n[AGENTS.md truncated: instruction byte limit reached.]"

# Constants for content size limits
MAX_AGENTS_BYTES = 32 * 1024
MAX_CATALOG_CHARS = 8_000
MAX_INSTRUCTIONS_BYTES = 64 * 1024
MAX_TOOL_RESULT_BYTES = 20 * 1024
MAX_TOOL_CONTENT_BYTES = MAX_TOOL_RESULT_BYTES * 4 // 5
MAX_ATTACHMENT_CONTENT_BYTES = 64 * 1024
MAX_FETCH_BYTES = 10 * 1024 * 1024
MAX_OUTPUT_CHARS = 1_000_000
CONTENT_PREVIEW_MAX_CHARS = 2_000
CONTENT_PREVIEW_MAX_LINES = 20
TOOL_CALL_VALUE_MAX_CHARS = 20

# UI constants
RENDER_MARKDOWN = True
TABULAR_MAX_WIDTH = 120
COLUMNS_THRESHOLD = 9

# Command execution timeout in seconds
COMMAND_TIMEOUT_SECONDS = 30

# Error handling and recovery
DEFAULT_MAX_RETRIES = 2

# Observability defaults
DEFAULT_TELEMETRY_QUEUE_CAPACITY = 4_096
DEFAULT_TELEMETRY_BATCH_SIZE = 128
DEFAULT_TELEMETRY_FLUSH_SECONDS = 0.1
DEFAULT_TELEMETRY_SHUTDOWN_TIMEOUT = 2.0
DEFAULT_TELEMETRY_SQLITE_BUSY_TIMEOUT_MS = 2_500
DEFAULT_OPERATIONAL_LOG_LEVEL = "INFO"
DEFAULT_OPERATIONAL_LOG_BYTES = 5 * 1024 * 1024
DEFAULT_OPERATIONAL_LOG_BACKUPS = 3
PRIVATE_DIRECTORY_MODE = 0o700
PRIVATE_FILE_MODE = 0o600

# Model discovery
MODEL_CATALOG_CACHE_SECONDS = 5.0
