"""Define shared application constants."""

from pathlib import Path

APP_DIRECTORY = Path(".loop")
SESSION_DATABASE_FILENAME = "sessions.db"
PERMISSIONS_FILENAME = "permissions.yaml"
PERMISSIONS_AUDIT_FILENAME = "permissions-audit.jsonl"

DEFAULT_AGENTS_FILENAME = "AGENTS.md"
DEFAULT_SKILL_FILENAME = "SKILL.md"
DEFAULT_SKILLS_DIRECTORY = Path(".agents/skills")
GIT_DIRECTORY = Path(".git")
AGENT_IGNORE_FILENAME = ".agentignore"
GIT_IGNORE_FILENAME = ".gitignore"
IGNORE_FILENAMES = (GIT_IGNORE_FILENAME, AGENT_IGNORE_FILENAME)

MAX_AGENTS_BYTES = 32 * 1024
MAX_CATALOG_CHARS = 8_000
MAX_INSTRUCTIONS_BYTES = 64 * 1024
MAX_TOOL_RESULT_BYTES = 20 * 1024
MAX_TOOL_CONTENT_BYTES = MAX_TOOL_RESULT_BYTES * 4 // 5
MAX_FETCH_BYTES = 10 * 1024 * 1024
MAX_OUTPUT_CHARS = 1_000_000
CONTENT_PREVIEW_MAX_CHARS = 2_000
CONTENT_PREVIEW_MAX_LINES = 20
COMMAND_TIMEOUT_SECONDS = 30

RESOURCE_DIRECTORIES = ("references", "scripts", "assets")
TRUNCATION_MARKER = "\n\n[AGENTS.md truncated: instruction byte limit reached.]"
