"""Expose tool permission policy models and management."""

__all__ = [
    "Action",
    "ApprovalChoice",
    "AuthorizationResult",
    "CommandAnalysis",
    "CommandFinding",
    "CommandInspection",
    "CommandMatcher",
    "CommandReviewStatus",
    "Decision",
    "FileKind",
    "FileManifestEntry",
    "FileTarget",
    "NetworkTarget",
    "Operation",
    "OperationPlan",
    "OperationPlanner",
    "Operations",
    "PermissionArtifactError",
    "PermissionCommands",
    "PermissionConfiguration",
    "PermissionConfigurationError",
    "PermissionLoadFailure",
    "PermissionLoadPolicy",
    "PermissionLoadResult",
    "PermissionManager",
    "PermissionPreset",
    "PermissionPresetError",
    "PermissionRecorder",
    "PermissionRule",
    "PolicyDecision",
    "PolicyLimitOverrides",
    "PolicyLimits",
    "PolicyScope",
    "PresetMetadata",
    "PresetReplacementPreview",
    "PresetRule",
    "PresetSource",
    "ProcessBoundary",
    "ProcessTarget",
    "ProtectedWorkspacePaths",
    "SQLitePermissionAudit",
    "SessionPolicyOverrides",
    "SessionTarget",
    "UserPermissionConfiguration",
    "match_destructive_command",
    "match_git_mutation",
    "protected_workspace_paths",
]

from .audit import SQLitePermissionAudit
from .commands import PermissionCommands
from .inspection import (
    CommandAnalysis,
    CommandInspection,
    CommandMatcher,
    match_destructive_command,
    match_git_mutation,
)
from .manager import PermissionManager
from .models import (
    Action,
    ApprovalChoice,
    AuthorizationResult,
    CommandFinding,
    CommandReviewStatus,
    Decision,
    FileKind,
    FileManifestEntry,
    FileTarget,
    NetworkTarget,
    Operation,
    OperationPlan,
    OperationPlanner,
    Operations,
    PermissionArtifactError,
    PermissionConfiguration,
    PermissionConfigurationError,
    PermissionLoadFailure,
    PermissionLoadPolicy,
    PermissionLoadResult,
    PermissionPreset,
    PermissionPresetError,
    PermissionRecorder,
    PermissionRule,
    PolicyDecision,
    PolicyLimitOverrides,
    PolicyLimits,
    PolicyScope,
    PresetMetadata,
    PresetReplacementPreview,
    PresetRule,
    PresetSource,
    ProcessBoundary,
    ProcessTarget,
    SessionPolicyOverrides,
    SessionTarget,
    UserPermissionConfiguration,
)
from .protection import ProtectedWorkspacePaths, protected_workspace_paths
