"""Provide utilities."""

__all__ = [
    "BoolValueHolder",
    "BoundedTextContent",
    "CachedContentMetadata",
    "ChoiceItem",
    "FloatValueHolder",
    "GenerationStop",
    "GenerationWatchdog",
    "IgnoreRule",
    "IgnoreRules",
    "IntValueHolder",
    "PathHolder",
    "PathInput",
    "PathReference",
    "PrivateRotatingTextFile",
    "Scalar",
    "ShutdownRequested",
    "StrValueHolder",
    "TextSearchCase",
    "TextSearchContext",
    "TextSearchMatch",
    "ValueHolder",
    "ValueReference",
    "VirtualPath",
    "as_utc",
    "base64_decode",
    "base64_encode",
    "bound_tool_result",
    "cached_metadata",
    "cached_path",
    "callable_hints",
    "callable_name",
    "canonical_path",
    "choice_items",
    "content_digest",
    "content_identity",
    "data_url",
    "decode_content_cursor",
    "encode_content_cursor",
    "filter_paths_by_globs",
    "find_project_root",
    "format_content_diff",
    "format_content_preview",
    "format_tool_call_arguments",
    "get_binary",
    "is_binary_file",
    "is_path_ignored",
    "iter_visible_paths",
    "json_encode",
    "list_terms",
    "local_now",
    "matches_digest",
    "normalized_key",
    "payload_digest",
    "read_bounded_text",
    "register_cached_metadata",
    "register_shutdown_signals",
    "safe_scalar",
    "search_text_paths",
    "sha256_digest",
    "snippet",
    "store_content",
    "store_text_stream",
    "utc_now",
    "validate_content_handle",
    "validate_term",
    "write_text_atomically",
]


from .callables import callable_hints, callable_name
from .content import (
    base64_decode,
    base64_encode,
    bound_tool_result,
    cached_metadata,
    cached_path,
    content_digest,
    content_identity,
    data_url,
    decode_content_cursor,
    encode_content_cursor,
    get_binary,
    json_encode,
    read_bounded_text,
    register_cached_metadata,
    store_content,
    store_text_stream,
    validate_content_handle,
)
from .dates import as_utc, local_now, utc_now
from .files import is_binary_file, write_text_atomically
from .generation import GenerationStop, GenerationWatchdog
from .hashing import matches_digest, payload_digest, sha256_digest
from .models import (
    BoundedTextContent,
    CachedContentMetadata,
    ChoiceItem,
    IgnoreRule,
    IgnoreRules,
    Scalar,
    TextSearchCase,
    TextSearchContext,
    TextSearchMatch,
)
from .normalization import normalized_key, safe_scalar
from .path import (
    VirtualPath,
    canonical_path,
    filter_paths_by_globs,
    find_project_root,
    is_path_ignored,
    iter_visible_paths,
)
from .rotating_file import PrivateRotatingTextFile
from .search import search_text_paths
from .signals import ShutdownRequested, register_shutdown_signals
from .text import (
    choice_items,
    format_content_diff,
    format_content_preview,
    format_tool_call_arguments,
    list_terms,
    snippet,
    validate_term,
)
from .value_holder import (
    BoolValueHolder,
    FloatValueHolder,
    IntValueHolder,
    PathHolder,
    PathInput,
    PathReference,
    StrValueHolder,
    ValueHolder,
    ValueReference,
)
